### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by user-grinch** [user-grinch/IMGEditor#1]
**Version 1.0 Release:**

- [x] Right click context menu
- [x] Popup message window
- [x] File renaming support
- [x] File import/ exporting
- [x] Dark mode theme
- [x] Multiselection in finder
- [x] Add progress bar
- [x] Setup github actions for daily builds
- [x] Context menu for multiselection
- [x] Add hold shift multiselection
- [x] Support for archive rebuilding/saving
- [x] Fix context menus going under the window
- [x] Add color options in settings
- [x] Add support for ini
- [x] Switch to freetype fonts
- [x] Optimize & reduce CPU usage for large archives
- [x] Export selected
- [x] Size scaling
- [x] Support for IMG v1 (GTA III & Vice City)
- [ ] Support for Fastman92's IMG format
- [x] Import and replace
- [x] Lock popup windows on top
